apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-result-service
spec:
  selector:
    app: {{ .Release.Name }}-node-result
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-result-srv
  type: ClusterIP
