{{- if .Values.dataPopulatorJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "blaze.fullname" . }}-node-fhir-test-data-populator
spec:
  template:
    spec:
      initContainers:
        - name: {{ include "blaze.fullname" . }}-node-fhir-test-data-populator-init-wait
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              for i in $(seq 1 5); do
                wget --spider -q "{{ include "blaze.fhirBaseURL" . }}" && break || sleep 60;
              done
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers:
        - name: {{ include "blaze.fullname" . }}-node-fhir-test-data-populator
          image: ghcr.io/privateaim/node-fhir-test-data-populator:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLEAR_TESTDATA_DIRS
              value: "true"
            - name: ENABLE_GENERATE_SYNTHEA_DATA
              value: "true"
            - name: N_PATIENTS
              value: {{ printf "%.0f" .Values.dataPopulatorJob.env.SYNTHEA_N_PATIENTS | default 10 | quote }}
            - name: SEED
              value: {{ printf "%.0f" .Values.dataPopulatorJob.env.SYNTHEA_SEED | default 3256262546 | quote }}
            - name: CLINICIAN_SEED
              value: {{ printf "%.0f" .Values.dataPopulatorJob.env.SYNTHEA_CLINICIAN_SEED | default 3726451 | quote }}
            - name: TIMEOUT
              value: "{{ .Values.dataPopulatorJob.env.TIMEOUT | default "1" }}"
            - name: ENABLE_PROCESS_TESTDATA
              value: "true"
            - name: GZIP_PROCESSED_OUTPUT_FILES
              value: "true"
            - name: REMOVE_INPUTFILES_PROCESSING
              value: "true"
            - name: RELEVANT_RESOURCES
              value: "Patient,Encounter,Observation,Condition,DiagnosticReport,Medication,MedicationAdministration,Procedure"
            - name: ENABLE_SENT_DATA_TO_FHIR
              value: "true"
            - name: GZIPPED_FHIR_SEND_INPUT_FILES
              value: "true"
            - name: REMOVE_INPUTFILES_FHIR_SENDING
              value: "true"
            - name: FHIR_URL
              value: "{{ include "blaze.fhirBaseURL" . }}"
            - name: FHIR_USER
              value: "''"
            - name: FHIR_PW
              value: "''"
      restartPolicy: Never
{{- end }}    