# Global values
global:
  hub:
    endpoints:
      auth: https://auth.privateaim.dev
      core: https://core.privateaim.dev
      messenger: https://messenger.privateaim.dev
      storage: https://storage.privateaim.dev
    auth:
      robotUser:
      robotSecret:
  node:
    ingress:
      enabled: true
      hostname: "https://my.domain.de"
  keycloak:
    ## @param global.keycloak.hostname Hostname for a separate instance of keycloak. Overrides the /keycloak subpath
    ## Leave this blank unless you want to use your own IDP
    hostname:

# keycloak values
keycloak:
  auth:
    adminUser: admin
    adminPassword: admin
