apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-local-minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-minio
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-minio
    spec:
      containers:
        - name: {{ .Release.Name }}-local-minio
          image: bitnami/minio:2024.1.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http-s3
          env:
            - name: MINIO_ROOT_USER
              value: {{ required "MinIO user must be set." .Values.env.MINIO_ACCESS_KEY | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ required "MinIO password must be set." .Values.env.MINIO_SECRET_KEY | quote }}
            - name: MINIO_DEFAULT_BUCKETS
              value: {{ required "MinIO bucket must be set." .Values.env.MINIO_BUCKET | quote }}
