apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-local-minio-service
spec:
  type: NodePort  # setting nodePort later is optional
  selector:
    app: {{ .Release.Name }}-minio
  ports:
    - protocol: TCP
      port: 9000  # port of this service
      targetPort: http-s3  # port on the pod
