{{- if not .Values.hub.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-results-robot-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  robotSecret: {{ required "A robot secret for the Hub is required." (include "results.hub.robotSecret" .) }}
{{- end }}
