apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-result-service
spec:
  selector:
    app: node-result
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP