apiVersion: v1
kind: Service
metadata:
  name: {{ include "components.fullname" "ui"}}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "ui"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - name: ui
    port: 3000
  selector:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "ui"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
