# Only created if idp.existingSecret not defined

{{- if not .Values.idp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "components.fullname" "ui-keycloak-secret"}}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "ui-keycloak-secret"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ include "components.fullname" "ui"}}
type: Opaque
data:
  nodeUiClientSecret: {{ include "ui.keycloak.clientSecret" . }}
{{- end }}
