apiVersion: v1
kind: Secret
metadata:
  name: {{ include "components.fullname" "result-service-hub-auth"}}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "result-service-hub-auth"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ include "components.fullname" "result-service"}}
data:
  robotSecret: {{ required "A robot secret for the Hub is required." (include "results.hub.robotSecret" .) }}
