apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-node-result-service-hub-auth
data:
  robotSecret: {{ required "A robot secret for the Hub is required." (include "results.hub.robotSecret" .) }}
