apiVersion: v1
kind: Service
metadata:
  name: {{ include "components.fullname" "result-service"}}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "result-service"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "result-service"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-result-srv
  type: ClusterIP
