apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-message-broker-db
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: flame
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  ports:
    - port: 27017
      targetPort: 27017
