apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-node-message-broker-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: flame
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  serviceName: {{ .Release.Name }}-node-message-broker-db
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: flame
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: flame
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      restartPolicy: "Always"
      containers:
        - name: {{ .Release.Name }}-node-message-broker-db
          image: mongo:7.0.5@sha256:fcde2d71bf00b592c9cabab1d7d01defde37d69b3d788c53c3bc7431b6b15de8
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "message-broker"
            - name: TZ
              value: {{ .Values.common.timezone | default "Europe/Berlin" | quote }}
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - 'db.runCommand("ping").ok'
                - --quiet
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            initialDelaySeconds: 30
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - 'db.runCommand("ping").ok'
                - --quiet
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          volumeMounts:
            - name: storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteMany"]
        {{- if .Values.common.storageClassName }}
        # Only use this if a storage class name is defined. Otherwise, use the default one within the cluster.
        storageClassName: {{ .Values.common.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ (.Values.broker_db).storageSizeMi | default 100 }}Mi
