apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-message-broker
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flame
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: flame
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: flame
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      restartPolicy: "Always"
      containers:
        - name: {{ .Release.Name }}-node-message-broker
          image: ghcr.io/privateaim/node-message-broker:{{ .Chart.AppVersion }}
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: AUTH_JWKS_URL
              value: {{ required "A valid JWKS URL for Keycloak is required." .Values.broker.AUTH_JWKS_URL }}
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Release.Name}}-node-message-broker-db:27017"
            - name: MONGO_DB_NAME
              value: "message-broker"
            - name: HUB_BASE_URL
              value: {{ required "A valid HUB API base URL is required." .Values.broker.HUB_BASE_URL | default "https://api.privateaim.net/" | quote}}
            - name: HUB_AUTH_BASE_URL
              value: {{ required "A valid HUB Auth base URL is required." .Values.broker.HUB_AUTH_BASE_URL | default "https://auth.privateaim.net/" | quote }}
            - name: HUB_AUTH_ROBOT_ID
              value: {{ required "A robot ID for the Hub is required." (include "broker.hub.robotUser") | quote }}
            - name: HUB_AUTH_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name}}-node-message-broker-hub-auth
                  key: robot-secret
            # DO NOT USE THIS IN PRODUCTION!!! This is just for internal testing purposes.
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 10
