apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-node-message-broker-hub-auth
data:
  robot-secret: {{ required "A secret associated with the HUB Auth robot id .Values.broker.HUB_AUTH_ROBOT_ID is required." (include "broker.hub.robotSecret") | b64enc }}
