apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-message-broker
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-node-message-broker
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flame
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  ports:
    - port: 80
      targetPort: 8080
