apiVersion: v1
kind: Secret
metadata:
  name: {{ include "components.fullname" "hub-auth" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "hub-auth" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  robotSecret: {{ required "A secret associated with a HUB auth robot account is required." .Values.global.hubAuthRobotSecret | b64enc }}

