image:
  repository: kong
  tag: "3.6"

env:
  prefix: /kong_prefix/
  database: postgres
  # The default values for admin_listen include both ipv4 and ipv6 - if cluster does not support ipv6, it should be defined (minikube does not support ipv6)
  # admin_listen: "127.0.0.1:8001"

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
  tls:
    enabled: false
    servicePort: 443

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

proxy:
  enabled: true
  type: ClusterIP  
  http:
    enabled: true
    servicePort: 80
  tls:
    enabled: false
    servicePort: 443   

ingressController:
  enabled: false

# Sub-chart
postgresql:
  enabled: true
  auth:
    username: kong
    database: kong
    password: kong
    postgresPassword: gqKvPbLCmG