apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-po-service
spec:
  ports:
  - name: api
    port: 8000 # Selector to match the pods of your Python app deployment
  selector:
    component: po
    #version: {{ .Chart.AppVersion }}
    deployment-id: {{ .Release.Name }}