apiVersion: v1
kind: Service
metadata:
  name: hub-adaptor-gateway-service
  labels:
    component: gateway-service
    version: 0.1.0
    deployment-id:  hub-adaptor
spec:
  ports:
  - name: api
    port: 5000
  selector:
    component: gateway-service
    version: 0.1.0
    deployment-id:  hub-adaptor
