apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-adaptor-gateway-deployment
spec:
  selector:
    matchLabels:
      component: gateway-service
      version: 0.1.0
      deployment-id:  hub-adaptor
  replicas: 1
  template:
    metadata:
      labels:
        component: gateway-service
        version: 0.1.0
        deployment-id:  hub-adaptor
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/privateaim/node-hub-api-adapter:latest
          imagePullPolicy: IfNotPresent  # Maybe "Always" during debug
          ports:
            - containerPort: 5000
          env:
            - name: API_CLIENT_ID
              value: "api-client"
            - name: IDP_URL
              value: "http://keycloak-service:8080"  # To be replaced
            - name: IDP_REALM
              value: "flame"
            - name: RESULTS_SERVICE_URL
              value: "http://node-result-service:8080"  # To be properly filled in
            - name: HUB_SERVICE_URL
              value: "https://api.privateaim.net"
            - name: HUB_AUTH_SERVICE_URL
              value: "https://auth.privateaim.net"
            - name: HUB_USERNAME
              value: "admin"  # To be properly filled in
            - name: HUB_PASSWORD
              value: "start123"
          startupProbe:
            httpGet:
              path: /healthz
              port: http-result-srv
            failureThreshold: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-result-srv
            failureThreshold: 3
            periodSeconds: 10
