apiVersion: v1
kind: Service
metadata:
  name: hub-adapter-gateway-service
  labels:
    component: hub-adapter-service
    version: 0.1.0
    deployment-id:  hub-adapter
spec:
  ports:
  - name: api
    port: 5000
  selector:
    component: hub-adapter-service
    version: 0.1.0
    deployment-id:  hub-adapter
