apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: local-minio
          image: bitnami/minio:2024.1.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http-s3
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: result-service-env
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: result-service-env
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_DEFAULT_BUCKETS
              value: flame
