apiVersion: v1
kind: Service
metadata:
  name: node-result-service
spec:
  type: NodePort  # setting nodePort later is optional
  selector:
    app: node-result
  ports:
    - protocol: TCP
      port: 8080  # port of this service
      targetPort: http-result-srv  # port on the pod
