apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-po-service
spec:
  selector:
    app: po   # Selector to match the pods of your Python app deployment
  ports:
    - protocol: TCP
      port: 8000         # Port on the service
      targetPort: 8000 # Port your Python app is listening on
  type: ClusterIP # TODO Change this to LoadBalancer, only for testing purposes