apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432  # Port of the service
      targetPort: 5432  # Port of the PostgreSQL pod
  type: ClusterIP