apiVersion: v1
kind: Service
metadata:
  name: {{ include "components.fullname" "hub-api-adapter"}}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "hub-api-adapter"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: api
      port: 5000
  selector:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "hub-api-adapter"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
