{{- if or .Values.global.node.ingress.enabled .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "components.fullname" "hub-api-adapter"}}
  annotations:
    # TODO: this does not work for everyone as it requires an NGINX ingress controller!!!
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "hub-api-adapter"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
    - host: {{ regexReplaceAll "^https?://(.*)" (include "adapter.ingress.hostname" .) "${1}" }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "components.fullname" "hub-api-adapter"}}
                port:
                  number: 5000
{{- end }}