# Only created if idp.existingSecret not defined

{{- if not .Values.idp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hub-adapter-keycloak-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "hub-api-adapter"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  hubAdapterClientSecret: {{ include "adapter.keycloak.clientSecret" . }}
{{- end }}
