{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-hub-adapter-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    component: hub-adapter-service
    version: {{ .Chart.AppVersion }}
    deployment-id:  {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-hub-adapter-service
                port:
                  number: 5000
{{- end }}