apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hub-adapter-deployment
spec:
  selector:
    matchLabels:
      component: hub-adapter-service
      version: {{ .Chart.AppVersion }}
      deployment-id:  {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        component: hub-adapter-service
        version: {{ .Chart.AppVersion }}
        deployment-id:  {{ .Release.Name }}
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/privateaim/node-hub-api-adapter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: healthcp
          env:
            - name: API_ROOT_PATH
              value: {{ (include "adapter.root.path" .) | default "" }}
            - name: API_CLIENT_ID
              value: {{ .Values.idp.clientId | default "hub-adapter" | quote }}
            - name: API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adapter.keycloak.secretName" . }}
                  key: {{ include "adapter.keycloak.secretKey" . }}
            - name: IDP_URL
              value: {{ include "adapter.keycloak.endpoint" . }}
            - name: IDP_REALM
              value: {{ .Values.idp.realm | default "flame" | quote }}  # To be replaced
            - name: RESULTS_SERVICE_URL
              value: {{ include "adapter.results.endpoint" . }}
            - name: PODORC_SERVICE_URL
              value: {{ include "adapter.po.endpoint" . }}
            - name: KONG_ADMIN_SERVICE_URL
              value: {{ include "adapter.kong.endpoint" . }}
            - name: HUB_SERVICE_URL
              value: {{ ( include "adapter.hub.coreApi" .) | default "https://core.privateaim.dev" | quote }}
            - name: HUB_AUTH_SERVICE_URL
              value: {{ ( include "adapter.hub.authApi" .) | default "https://auth.privateaim.dev" | quote }}
            - name: HUB_ROBOT_USER
              value: {{ required "A robot ID for the Hub is required." (include "adapter.hub.robotUser" .) | quote }}  # To be properly filled in
            - name: HUB_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adapter.hub.secretName" . }}
                  key: "robotSecret"
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthcp
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
