apiVersion: v1
kind: Secret
metadata:
  name: hub-adapter-keycloak-secret
# stringData:
#   kcsecret: {{ randAlphaNum 24 | b64enc | quote }}
data:
  keycloak: cFR2THJCS3V5MHZ4cnV2VXByd3NYcEV0dzg0ZEROOUM= # Same as hardcoded secret in keycloak init realm
