# Only created if idp.existingSecret not defined

{{- if not .Values.idp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hub-adapter-keycloak-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  hubAdapterClientSecret: {{ include "adapter.keycloak.clientSecret" . }}
{{- end }}

---

{{- if not .Values.hub.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hub-adapter-robot-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  robotSecret: {{ required "A robot secret for the Hub is required." (include "adapter.hub.robotSecret" .) }}
{{- end }}