apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name:  {{ include "components.fullname" "pod-orchestration"}}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "pod-orchestration"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: ["networking.k8s.io"] # indicates the network API group
  resources: ["networkpolicies"]
  verbs: ["*"]
- apiGroups: ["apps"] # indicates the apps API group
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""] # indicates the core API group
  resources: ["pods", "secrets", "services", "configmaps"]
  verbs: ["*"]
