apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-po-keycloak-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  podOrcClientSecret: {{ include "po.keycloak.clientSecret" . }}
